server:
   port: 9999

spring:
   cloud:
      stream:
         bindings:
            output: 
               destination: productoes

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true

#zuul:
#   servletPath: ${spring.application.name}
