server:
   port: 0

message: MENSAJE DESDE MEETUP LIVE CODING SESION

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:1111/eureka}
   instance:
      preferIpAddress: true
