server:
   port: ${PORT:9999}

spring:
   cloud:
      stream:
         bindings:
            output:
               destination: productoes

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1111/eureka

zuul:
   servletPath: ${spring.application.name}
