server:
   port: 0

#spring:
#   cloud:
#      stream:
#         bindings:
#            output: productoes

eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:1111/eureka}
   instance:
      preferIpAddress: true

#zuul:
#   servletPath: ${spring.application.name}
