server:
   port: ${PORT:8000}

spring:
   cloud:
      stream:
         bindings:
            input: productoes

message: MENSAJE DESDE YAML

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1111
